[package]
name = "eightfish"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eightfish-derive = { version = "0.1.0", path = "eightfish-derive" }
typemap = "0.3"
