spin_version = "1"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A redis application."
name = "redis-worker"
trigger = {type = "redis", address = "redis://localhost:6379"}
version = "0.1.0"

[[component]]
id = "redis-worker"
source = "target/wasm32-wasi/release/redis-worker.wasm"
[component.trigger]
channel="spin2proxy"
[component.build]
command = "cargo build --target wasm32-wasi --release"
